# Generated by Django 3.0.8 on 2020-08-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200818_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taco',
            name='favorite',
        ),
        migrations.AddField(
            model_name='taco',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite_taco', to='home.User'),
        ),
        migrations.RemoveField(
            model_name='taco',
            name='tacos_for',
        ),
        migrations.AddField(
            model_name='taco',
            name='tacos_for',
            field=models.ManyToManyField(related_name='taco_history', to='home.User'),
        ),
    ]
